version: '3'

services:
  nginx:
    build: ./.nginx
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - '8080:80'
    networks:
      - app-network

  node1:
    image: nodeapp:1.0
    ports:
      - '3000:3000'
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  node2:
    image: nodeapp:1.0
    ports:
      - '3001:3000'
    environment:
      - INSTANCE=node2
    networks:
      - app-network

  node3:
    image: nodeapp:1.0
    ports:
      - '3002:3000'
    environment:
      - INSTANCE=node3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
